---
# Production environment override
services:
  ecobattle:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    networks:
      - default
      - nginx
  
networks:
  nginx:
    name: ${NETWORK_NAME:-gateway}
    external: true
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420
