---
# Production environment override
services:
  ecobattle:
    build:
      context: .
      target: frankenphp_prod
    networks:
      - default
      - nginx
    env_file:
      - .env
      - .env.local
  
networks:
  nginx:
    name: ${NETWORK_NAME:-gateway}
    external: true
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420
